name: Setup python env
description: Set up Python with uv and nox

inputs:
  python-version:
    description: Python version to use
    required: true
  uv-version:
    description: uv version to install
    required: false
    default: "v7.1.3"
  nox-version:
    description: nox version to install
    required: false
    default: "2025.11.12"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@${{ inputs.uv-version }}

    - name: Install nox
      shell: bash
      run: pip install nox==${{ inputs.nox-version }}
